### ISSUE TITLE
Warnings and a "bad" looking render

### ISSUE THREAD

**Issue by jefftrull** [jefftrull/ColladaOgreImporter#1]
@Nidhin009 reports (via email) that [this model](http://tf3dm.com/download-page.php?url=bmw-x5-1542) looks bad - specifically the textures do, and I concur.  Also the conversion produces a number of warning messages like:

`Could not find effect 14216376763747914595 in storage` (x12)

and

`Geometry instance with object id 8359456016315925126 is NOT a mesh we know about` (x2)

**Comment by jefftrull** [comment]
As you can see the warnings, at least, seem to be due to an upstream bug.

**Comment by Nidhin009** [comment]
Dear Jeff,

I created a cube in blender. I exported it as a dae file. And imported in my application using ColladaOgre importer. It says as below

COLLADA WARNING: Scene node has 5 transformations - we only handle 0 or 1
COLLADA WARNING: Scene node has 5 transformations - we only handle 0 or 1

And nothing is visible in the scene.

**Comment by Nidhin009** [comment]
I have few more queries. 

a) Will it support the dae files exported from 3D max. 
b) What all things we need to check when exporting from 3D max? 
c) Do we need to explicitly give the lights in OGRE? 
d) If there are lights in .dae files, will this parser add it to scenemanger?
e) Just like robot.mesh in OGRE, can I give animations in dae file and can I use it in OGRE? 

Nidhin

**Comment by Nidhin009** [comment]
http://stackoverflow.com/questions/42509724/ogre-collada-library-source

**Comment by jefftrull** [comment]
All very good questions but we should really separate these into different issues.  Thanks :)

**Comment by jefftrull** [comment]
Some of the ugliness can be explained by the fact that this is exported by FBX which has known issues with the transparency tag, see [here](https://github.com/mrdoob/three.js/issues/2210) and [here](https://forums.autodesk.com/t5/fbx-forum/problems-with-collada-exports/td-p/4169868?nobounce).  I am looking at doing the same workaround I do for Sketchup.

**Comment by jefftrull** [comment]
Workaround installed.  Looks a lot better, I think.  There is still an issue with the wheels and windscreen, which have texture coordinates but no texture attached - thus the white color.

Edit: _I should clarify that the white color is inserted by my code when no material is found for a geometry_

**Comment by jefftrull** [comment]
Because the warnings are due to an upstream bug, and I've added a workaround for the FBX exporter, I believe this bug should be closed.  The white sections of the car are due to missing materials in the .dae file.
